routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('user', 'UserController');

Route::resource('candidates', 'CandidatesController')->middleware('auth');
Route::get('candidates/changeuser/{cid}/{uid?}', 'CandidatesController@changeUser')->name('candidate.changeuser');
Route::get('candidates/changestatus/{cid}/{sid}', 'CandidatesController@changeStatus')->name('candidates.changestatus')->middleware('auth');

Route::get('mycandidates', 'CandidatesController@myCandidates')->name('candidates.mycandidates')->middleware('auth');

Route::get('sortages', 'CandidatesController@sortages')->name('candidates.sortages')->middleware('auth');

Route::get('listofusers', 'UserController@listofusers')->name('users.listofusers')->middleware('auth');

Route::get('candidates/delete/{id}', 'CandidatesController@destroy')->name('candidate.delete');

Route::get('user/delete/{id}', 'UserController@destroy')->name('user.delete');

Route::get('notfit', 'CandidatesController@notfit')->name('candidates.notfit')->middleware('auth');

Route::get('candidates/addcomment/{id}', 'CandidatesController@addcomment')->name('candidates.addcomment')->middleware('auth');

Route::get('history', 'CandidatesController@history')->name('candidate.history')->middleware('auth');


 
Route::get('/hello', function (){
    return 'Hello Larevel';
}); 

Route::get('/student/{id}', function ($id  = 'No student found'){
    return 'We got student with id '.$id;
});

Route::get('/car/{id?}', function ($id  = null){
    if(isset($id)){
        //TODO: validate for integer  
        return "We got car $id";
    } else {
        return 'We need the id to find your car';
    }
});


Route::get('/comment/{id}', function ($id) {
    return view('comment', compact('id'));
});

Route::get('/users/{email}/{name?}', function ($email,$name = null) {
    if(!isset($name)){
        $name = 'Mising name';
    }
    return view('users', compact('email','name'));
});




#example
Route::get('/users1/{name?}/{email}', function ($name = null, $email) {
    if(!isset($name)){
        $name = 'Mising name';
    }
    return view('users', compact('email','name'));
});























Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{

    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'email', 'password','department_id','user_add_id'];

    public function candidates(){
        return $this->hasMany('App\Candidate');
    }

    public function department(){
        return $this->belongsTo('App\Department');
    }  
    
    public function roles(){
        return $this->belongsToMany('App\Role','userroles');        
    }    
    
    public function isAdmin(){
        $roles = $this->roles;
        if(!isset($roles)) return false;
        foreach($roles as $role){
            if($role->name === 'admin') return true; 
        } 
        return false; 
    }

    public function isManager(){
        $roles = $this->roles;
        if(!isset($roles)) return false;
        foreach($roles as $role){
            if($role->name === 'manager') return true; 
        } 
        return false; 
    }



    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use App\Candidate;
use App\User;
use App\Status;
use App\Department;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Hash;



class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    
    
    public function listofusers()
    {   
        $users = User::all();
        $departments = Department::all();        
        return view('users.listofusers', compact('users', 'departments'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $departments = Department::all();
        return view('users.create', compact('departments'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
                $userId = Auth::id();

        User::create([
            'name' => $request['name'],
            'email' => $request['email'],
            'password' => Hash::make($request['password']),
            'department_id' => $request['department_id'],
            'user_add_id' => $userId,

        ]);

        return redirect('candidates');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        Gate::authorize('edit-delete-user');
        $user = User::findOrFail($id);
        return view('users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $user = User::findOrFail($id);
        $user->update($request->all());
        $users = User::all();
        $departments = Department::all();
        return view('users.listofusers', compact('users','departments' ));  
     }
 

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Gate::authorize('edit-delete-user');
        $user = User::findOrFail($id);
        $user->delete(); 
        $users = User::all();
        $departments = Department::all();
        return view('users.listofusers', compact('users','departments' ));  
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('title', 'Create candidate')

@section('content')
        <h1>Add User</h1>
        <form method = "post" action = "{{action('UserController@store')}}">
        @csrf 
        <div class="form-group">
            <label for = "name">User name</label>
            <input type = "text" class="form-control" name = "name">
        </div>     
        <div class="form-group">
            <label for = "email">User email</label>
            <input type = "text" class="form-control" name = "email">
        </div> 
        <div class="form-group">
            <label for = "password">User password</label>
            <input type = "int" class="form-control" name = "password">
        </div> 
        
        <div class="form-group row">
            <label for="department_id" class="col-md-4 col-form-label text-md-right">Department</label>
             <div class="col-md-6">
                <select class="form-control" name="department_id">                                                                         
                    @foreach ($departments as $department)
                        <option value="{{ $department->id }}"> 
                            {{ $department->name }} 
                         </option>
                    @endforeach    
                    
                </select>
            </div>
        <div>
            <input type = "submit" name = "submit" value = "Create User">
        </div>                       
        </form>    
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit candidate')

@section('content')       
       <h1>Edit user</h1>
        <form method = "post" action = "{{action('UserController@update',$user->id)}}">
        @csrf
        @METHOD('PATCH')
        <div class="form-group">
            <label for = "name">User name</label>
            <input type = "text" class="form-control" name = "name" value = {{$user->name}}>
        </div>     
        <div class="form-group">
            <label for = "email">user email</label>
            <input type = "text" class="form-control" name = "email" value = {{$user->email}}>
        </div> 
        <div>
            <input type = "submit" name = "submit" value = "Update user">
        </div>                       
        </form>    
    </body>
</html>
@endsection

resources/views/users/listofusers.blade.php
@extends('layouts.app')

@section('title', 'Candidates')

@section('content')
<h1>List of users</h1>

<table class = "table table-dark">
    <tr>
        <th>user</th><th>department</th><th>user_add_id</th>
    </tr>
    @foreach($users as $user)
        <tr>
            <td>{{$user->name}}</td>
            <td>{{$user->department->name}}</td>
            <td>{{$user->user_add_id}}</td>

            <td>
                <a href = "{{route('user.edit',$user->id)}}">Edit</a>
            </td> 
            <td>
                <a href = "{{route('user.delete',$user->id)}}">Delete</a>
            </td>                                                               
        </tr>
    @endforeach
</table>
@endsection